<?php

putenv('DISPLAY_ERRORS_DETAILS=' . true);

putenv('UPTECHNOLOGY1_PG_HOST=');

putenv('UPTECHNOLOGY1_PG_DBNAME=');

putenv('UPTECHNOLOGY1_PG_USER=');

putenv('UPTECHNOLOGY1_PG_PASSWORD=');

putenv('UPTECHNOLOGY1_PG_PORT=');

putenv('JWT_SECRET_KEY=');
?>